### ISSUE TITLE
cdv pushtx ./spend_bundle.json returns Error

### ISSUE THREAD

**Issue by geraldneale** [Chia-Network/chia-dev-tools#10]
Error: No such command 'pushtx'

This is an example copied directly from the README.

$ cdv --version
cdv, version 1.0.2

**Comment by geraldneale** [comment]
I think I found the problem. The following works:

cdv rpc pushtx ./spend_bundle.json

I think you simply forgot to indicate "rpc".

**Comment by Quexington** [comment]
The README has been updated with this thank you!
