### ISSUE TITLE
cdv rpc should return valid json

### ISSUE THREAD

**Issue by kimsk** [Chia-Network/chia-dev-tools#14]
`pprint` helps with formatting, but it doesn't produce a valid json. We could use `print` and `json.dumps` to produce a valid json. I have some sample code [here](https://github.com/kimsk/chia-dev-tools/commit/099274ef928d11777e7cc06ab687d7fa678085a2).

![image](https://user-images.githubusercontent.com/116863/130311000-c588b985-05a9-4bdb-b474-3e54baad0b65.png)

**Comment by Quexington** [comment]
Thank you for the comment this was fixed in https://github.com/Chia-Network/chia-dev-tools/pull/16
