### ISSUE TITLE
Example in ReadMe uses invalid coin

### ISSUE THREAD

**Issue by miketheneale** [Chia-Network/chia-dev-tools#15]
cdv rpc coinrecords --by id e16dbc782f500aa24891886779067792b3305cff8b873ae1e77273ad0b7e6c05

The coin listed above is not valid; it produces an empty result.

0x6ce8fa56321d954f54ba27e58f4a025eb1081d2e1f38fc089a2e72927bcde0d1

This one works^

**Comment by Quexington** [comment]
Thank you for the comment, this was fixed in https://github.com/Chia-Network/chia-dev-tools/pull/16
