### ISSUE TITLE
Uninstalling chia-blockchain 1.3.0 after installation

### ISSUE THREAD

**Issue by jorgetu** [Chia-Network/chia-dev-tools#30]
I have installed chia-blockchain 1.3.0
After it I Install chia-dev-tools using 
pip install chia-dev-tools

And the log says:
Attempting uninstall: chia-blockchain
    Found existing installation: chia-blockchain 1.3.0
    Uninstalling chia-blockchain-1.3.0:
      Successfully uninstalled chia-blockchain-1.3.0
Successfully installed blspy-1.0.6 chia-blockchain-1.2.11 chia-dev-tools-1.0.6 

It seems it is installing chia-blockchain 1.3.0- and installing chia-blockchain-1.2.11

**Comment by Quexington** [comment]
Yes, this library is pinned to a specific version of `chia-blockchain` I'm currently in the process of upgrading it to 1.3.0, but this will always be the case.  It may be better to install with `--no-deps` and then install the remaining dependencies manually, or to use a separate `venv`.
