### ISSUE TITLE
chia-blockchain 1.5.1 error

### ISSUE THREAD

**Issue by zhugcx** [Chia-Network/chia-dev-tools#45]
pip install chia-dev-tools

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cat-admin-tool 0.0.1 requires chia-blockchain==1.5.0, but you have chia-blockchain 1.5.1 which is incompatible.

**Comment by jack60612** [comment]
this is caused by a venv conflict, try using a separate environment.
