### ISSUE TITLE
fullnode rpc get_puzzle_and_solution info error

### ISSUE THREAD

**Issue by zhugcx** [Chia-Network/chia-dev-tools#46]
curl --insecure --cert ~/.chia/testnet10/config/ssl/full_node/private_full_node.crt --key ~/.chia/testnet10/config/ssl/full_node/private_full_node.key -d '{"coin_id": "0x47f1cd7198c178ce86e97efe44add10c8587d088ed817fbbe049ec862619368e", "height": 1489939}' -H "Content-Type: application/json" -X POST https://localhost:8555/get_puzzle_and_solution | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   800  100   700  100   100  46585   6655 --:--:-- --:--:-- --:--:-- 57142
{
    "error": "can't cast <class 'chia.types.blockchain_format.program.SerializedProgram'> (ff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b081e576328ffc00a4937afdec46ad07d1f66717d7bc1b766035539f981f956109a435793182b23bf31084741e2e5909f3ff018080) to bytes",
    "success": false
}

**Comment by Quexington** [comment]
This was a bug in the chia-blockchain repo and should be fixed in the latest release (or perhaps the next one)
