### ISSUE TITLE
Feature Request: disable Bitfield

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-dev-tools#47]
Would it be possible to add a flag to `cdv sim create` to disable Bitfield processing when creating plots? The reason for this request is that on virtual machines, Bitfield is sometimes (maybe always) not possible. 

```Caught plotting error: Bitfield plotting not supported by CPU```

Currently, in `chia/simulator/block_tools.py`, `args.nobitfield` is hard-coded to `False`. This request would create a command line flag to change this to `True`, thereby allowing plots to be created using virtual CPUs.

**Comment by Quexington** [comment]
https://github.com/Chia-Network/chia-dev-tools/pull/54
