### ISSUE TITLE
Attempt to change the block reward address fails

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-dev-tools#48]
My simulator has a wallet with the prefarm and a few block rewards:
```
Chia wallet show
Wallet height: 8
Sync status: Synced
Balances, fingerprint: 3446212044

Chia Wallet:
   -Total Balance:         21000012.0 txch (21000012000000000000 mojo)
   -Pending Total Balance: 21000012.0 txch (21000012000000000000 mojo)
   -Spendable:             21000012.0 txch (21000012000000000000 mojo)
   -Type:                  STANDARD_WALLET
   -Wallet ID:             1
```

Attempt to farm a block with a different reward address:
```
cdv sim farm -a txch1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqm6ksh7qddh
Farmed 1 Transaction blocks
Block Height is now: 9
```

The original wallet still received the farming reward:
```
chia wallet show
Wallet height: 9
Sync status: Synced
Balances, fingerprint: 3446212044

Chia Wallet:
   -Total Balance:         21000014.0 txch (21000014000000000000 mojo)
   -Pending Total Balance: 21000014.0 txch (21000014000000000000 mojo)
   -Spendable:             21000014.0 txch (21000014000000000000 mojo)
   -Type:                  STANDARD_WALLET
   -Wallet ID:             1
```

**Comment by danieljperry** [comment]
The RPC command works as expected:
`chia rpc full_node farm_block '{"address": "txch1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqm6ksh7qddh"}'`

The reward for the block farmed with this command goes to the correct address.

**Comment by jack60612** [comment]
I can't seem to replicate this, I think your wallet is just receiving the block reward from the previous block.
When you called farm_block using the rpc, you forgot to request a transaction block, so the reward for the previous block was not included.
