### ISSUE TITLE
Please provide `--network` option for `cdv rpc pushtx` to specify the network (for AGG_SIG_ME)

### ISSUE THREAD

**Issue by kimsk** [Chia-Network/chia-dev-tools#52]
`simulator0` has its own [`GENESIS_CHALLENGE`](https://github.com/Chia-Network/chia-dev-tools/blob/main/cdv/cmds/sim_utils.py#L122). However, when trying to use `cdv rpm pushtx`, it seems to use `mainnet` one only, so the spend bundle with valid aggregated signature on `simulator0` causes `BAD_AGGREGATE_SIGNATURE` error.

Providing `--network` option like in `cdv inspect spendbundles` command or change the default network to `simulator0` should help.

![image](https://user-images.githubusercontent.com/116863/193219648-7fd79cd9-48c7-442a-ab0f-cbd435fb88ec.png)

This is the spend bundle that I used.
```json
{
    "aggregated_signature": "0xb3feab7bdd8da63f90732994becc50f259ad69069e64000a12bfa4ce07270c97e65cd897d61ebee321f5a29dbd0e85c319903edd7e9dd07c3d30cb2ace34ad34f320d5168786899285079e868c1febcefe986af2a281b853b5a2bcdc2a57f89a",
    "coin_spends": [
        {
            "coin": {
                "amount": 1000000000001,
                "parent_coin_info": "0xdf2cf850264c22b8bfe7da999b56b8a6689c9ce25be52d0807fe12ed8c9e1b5b",
                "puzzle_hash": "0x6ee43a3c617c5a1ec62ffeff1b605fb53ecc81ba8ccd4024eaff9befc53c6145"
            },
            "puzzle_reveal": "0xff02ffff01ff02ffff01ff02ffff03ffff09ff12ff2f80ffff01ff04ffff04ff14ffff01ff648080ffff04ffff04ff16ffff04ff05ffff01ff8600e8d4a51000808080ffff04ffff04ff10ffff04ff0bffff01ff9072657475726e20746f2073656e646572808080ff80808080ffff01ff02ffff03ffff09ff1aff2f80ffff01ff04ffff04ff16ffff04ff3effff01ff8601d1a94a2001808080ffff04ffff04ff18ffff04ff17ff808080ffff04ffff04ff2effff04ff17ff808080ff80808080ffff01ff04ffff04ff1cffff04ff17ff808080ff808080ff018080ff0180ffff04ffff01ffffff323dff523fffff81ff01ff33ff3ea0eff07522495060c066f66f32acc2a77e3a3e737aca8baea4d1a64ea4cdc13da9ff018080ffff04ffff01a0d210b94e1c190321d74e68fa697a8da3dce5846bbaf9f2783ba345c431123387ffff04ffff01b096f75bf45d09491e8a5adaedbdb458f6ac46d9b6507a788fe58349f6eb2a56bfbc72bdd70a09eceb060b552f10fb1010ff01808080",
            "solution": "0xff84900ddeedff81ff80"
        }
    ]
}
```

**Comment by Quexington** [comment]
`cdv rpc pushtx` has no idea about what network it's pushing to so adding an option to it wouldn't help.  It's not very intuitive, but the simulator validates signatures with the mainnet genesis challenge even though it has it's own genesis challenge.  Sign things as if you're signing them for mainnet and you should be good.
